#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

define('ROOT_PATH', __DIR__  . '/../..');
define('APP_PATH',  __DIR__ );

require(ROOT_PATH . '/vendor/autoload.php');
require(ROOT_PATH . '/functions.php');

require(__DIR__   . '/environment.php');
require(ROOT_PATH . '/vendor/yiisoft/yii2/Yii.php');
require(ROOT_PATH . '/common/config/bootstrap.php');
require(__DIR__   . '/config/bootstrap.php');

\Yii::$container->setSingleton(\sys\interfaces\ConfiguratorInterface::class, \sys\components\Configurator::class);

$configurator = Yii::$container->get(\sys\interfaces\ConfiguratorInterface::class);
$configurator->setEnv(\sys\components\Configurator::CONSOLE);
$configurator->setCachePath(__DIR__ . '/runtime/cache_configurator');
$configurator->load([
    ROOT_PATH . '/common/config/main.php',
    ROOT_PATH . '/common/config/main-local.php',
    __DIR__   . '/config/console.php',
    __DIR__   . '/config/console-local.php'
]);

$application = new yii\console\Application($configurator->configure());
$exitCode = $application->run();
exit($exitCode);
